In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn .preprocessing import StandardScaler

In [3]:
dataset = pd.read_csv('churn_modelling.csv')
X = dataset.iloc[:,3:13].values
Y = dataset.iloc[:,13].values
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
X.shape

(10000, 10)

In [5]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [6]:
labelencoder_X_1 = LabelEncoder()
X[:,1] = labelencoder_X_1.fit_transform(X[:,1])
labelencoder_X_2 = LabelEncoder()
X[:,2] = labelencoder_X_2.fit_transform(X[:,2])

In [7]:
X

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [8]:
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()

c:\users\chaitanya chadha\appdata\local\programs\python\python36\lib\site-packages\sklearn\preprocessing\_encoders.py:363: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
c:\users\chaitanya chadha\appdata\local\programs\python\python36\lib\site-packages\sklearn\preprocessing\_encoders.py:385: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [9]:
X

array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [10]:
X.shape

(10000, 12)

In [11]:
X_train,X_test,Y_Train,Y_test= train_test_split(X,Y,test_size = 0.2 , random_state = 42)

In [12]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [13]:
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [14]:
classifier = Sequential()

In [15]:
classifier.add(Dense(units = 6, kernel_initializer='uniform', activation = 'relu', input_dim=12))

In [16]:
classifier.add(Dense(units = 6, kernel_initializer='uniform', activation = 'relu' ))

In [17]:
classifier.add(Dense(units = 1, kernel_initializer='uniform', activation = 'sigmoid'))

In [18]:
classifier.compile(optimizer = 'adam', loss= 'binary_crossentropy',metrics=['accuracy'])

In [20]:
classifier.fit(X_train,Y_Train,batch_size=10,epochs =500)

Epoch 1/500
8000/8000 [==============================] - 1s 91us/step - loss: 0.4961 - acc: 0.7972
Epoch 2/500
8000/8000 [==============================] - 0s 62us/step - loss: 0.4251 - acc: 0.8175
Epoch 3/500
8000/8000 [==============================] - 1s 65us/step - loss: 0.4179 - acc: 0.8240
Epoch 4/500
8000/8000 [==============================] - 0s 60us/step - loss: 0.4133 - acc: 0.8291
Epoch 5/500
8000/8000 [==============================] - 0s 59us/step - loss: 0.4109 - acc: 0.8316
Epoch 6/500
8000/8000 [==============================] - 0s 62us/step - loss: 0.4086 - acc: 0.8311
Epoch 7/500
8000/8000 [==============================] - 0s 61us/step - loss: 0.4072 - acc: 0.8319
Epoch 8/500
8000/8000 [==============================] - 1s 63us/step - loss: 0.4049 - acc: 0.8330
Epoch 9/500
8000/8000 [==============================] - 0s 58us/step - loss: 0.4018 - acc: 0.8312
Epoch 10/500
8000/8000 [==============================] - 1s 64us/step - loss: 0.3974 - acc: 0.8337
Epoch 11/

8000/8000 [==============================] - 2s 238us/step - loss: 0.3390 - acc: 0.8620
Epoch 83/500
8000/8000 [==============================] - 2s 195us/step - loss: 0.3376 - acc: 0.8617
Epoch 84/500
8000/8000 [==============================] - 2s 244us/step - loss: 0.3373 - acc: 0.8629
Epoch 85/500
8000/8000 [==============================] - 2s 245us/step - loss: 0.3365 - acc: 0.8637
Epoch 86/500
8000/8000 [==============================] - 2s 214us/step - loss: 0.3381 - acc: 0.8632
Epoch 87/500
8000/8000 [==============================] - 2s 242us/step - loss: 0.3381 - acc: 0.8592
Epoch 88/500
8000/8000 [==============================] - 2s 245us/step - loss: 0.3378 - acc: 0.8617
Epoch 89/500
8000/8000 [==============================] - 2s 240us/step - loss: 0.3383 - acc: 0.8590
Epoch 90/500
8000/8000 [==============================] - 2s 244us/step - loss: 0.3377 - acc: 0.8627
Epoch 91/500
8000/8000 [==============================] - 2s 247us/step - loss: 0.3372 - acc: 0.8634
Epo

8000/8000 [==============================] - 2s 230us/step - loss: 0.3362 - acc: 0.8621
Epoch 163/500
8000/8000 [==============================] - 2s 247us/step - loss: 0.3352 - acc: 0.8641
Epoch 164/500
8000/8000 [==============================] - 2s 232us/step - loss: 0.3338 - acc: 0.8635
Epoch 165/500
8000/8000 [==============================] - 2s 205us/step - loss: 0.3343 - acc: 0.8642
Epoch 166/500
8000/8000 [==============================] - 2s 253us/step - loss: 0.3354 - acc: 0.8637
Epoch 167/500
8000/8000 [==============================] - 2s 256us/step - loss: 0.3352 - acc: 0.8640
Epoch 168/500
8000/8000 [==============================] - 2s 232us/step - loss: 0.3359 - acc: 0.8637
Epoch 169/500
8000/8000 [==============================] - 2s 233us/step - loss: 0.3359 - acc: 0.8629
Epoch 170/500
8000/8000 [==============================] - 2s 246us/step - loss: 0.3348 - acc: 0.8645
Epoch 171/500
8000/8000 [==============================] - 2s 248us/step - loss: 0.3342 - acc: 0

8000/8000 [==============================] - 2s 237us/step - loss: 0.3333 - acc: 0.8651
Epoch 243/500
8000/8000 [==============================] - 2s 244us/step - loss: 0.3337 - acc: 0.8647
Epoch 244/500
8000/8000 [==============================] - 2s 240us/step - loss: 0.3329 - acc: 0.8644
Epoch 245/500
8000/8000 [==============================] - 2s 228us/step - loss: 0.3323 - acc: 0.8647
Epoch 246/500
8000/8000 [==============================] - 2s 200us/step - loss: 0.3334 - acc: 0.8645
Epoch 247/500
8000/8000 [==============================] - 2s 225us/step - loss: 0.3333 - acc: 0.8659
Epoch 248/500
8000/8000 [==============================] - 2s 245us/step - loss: 0.3324 - acc: 0.8641
Epoch 249/500
8000/8000 [==============================] - 2s 244us/step - loss: 0.3333 - acc: 0.8635
Epoch 250/500
8000/8000 [==============================] - 2s 243us/step - loss: 0.3326 - acc: 0.8661
Epoch 251/500
8000/8000 [==============================] - 2s 246us/step - loss: 0.3329 - acc: 0

8000/8000 [==============================] - 2s 200us/step - loss: 0.3331 - acc: 0.8637
Epoch 323/500
8000/8000 [==============================] - 2s 221us/step - loss: 0.3326 - acc: 0.8655
Epoch 324/500
8000/8000 [==============================] - 2s 193us/step - loss: 0.3330 - acc: 0.8680
Epoch 325/500
8000/8000 [==============================] - 2s 219us/step - loss: 0.3336 - acc: 0.8641
Epoch 326/500
8000/8000 [==============================] - 2s 189us/step - loss: 0.3322 - acc: 0.8641
Epoch 327/500
8000/8000 [==============================] - 2s 230us/step - loss: 0.3326 - acc: 0.8636
Epoch 328/500
8000/8000 [==============================] - 1s 180us/step - loss: 0.3327 - acc: 0.8642
Epoch 329/500
8000/8000 [==============================] - 1s 174us/step - loss: 0.3324 - acc: 0.8645
Epoch 330/500
8000/8000 [==============================] - 1s 178us/step - loss: 0.3337 - acc: 0.8642
Epoch 331/500
8000/8000 [==============================] - 2s 190us/step - loss: 0.3330 - acc: 0

8000/8000 [==============================] - 2s 242us/step - loss: 0.3322 - acc: 0.8650
Epoch 403/500
8000/8000 [==============================] - 2s 216us/step - loss: 0.3322 - acc: 0.8649
Epoch 404/500
8000/8000 [==============================] - 2s 203us/step - loss: 0.3326 - acc: 0.8642
Epoch 405/500
8000/8000 [==============================] - 1s 178us/step - loss: 0.3325 - acc: 0.8656
Epoch 406/500
8000/8000 [==============================] - 2s 197us/step - loss: 0.3318 - acc: 0.8631
Epoch 407/500
8000/8000 [==============================] - 2s 221us/step - loss: 0.3327 - acc: 0.8671
Epoch 408/500
8000/8000 [==============================] - 2s 231us/step - loss: 0.3321 - acc: 0.8652
Epoch 409/500
8000/8000 [==============================] - 2s 231us/step - loss: 0.3329 - acc: 0.8632
Epoch 410/500
8000/8000 [==============================] - 2s 225us/step - loss: 0.3330 - acc: 0.8642
Epoch 411/500
8000/8000 [==============================] - 1s 182us/step - loss: 0.3325 - acc: 0

8000/8000 [==============================] - 2s 249us/step - loss: 0.3329 - acc: 0.8621
Epoch 483/500
8000/8000 [==============================] - 2s 255us/step - loss: 0.3324 - acc: 0.8642
Epoch 484/500
8000/8000 [==============================] - 2s 254us/step - loss: 0.3322 - acc: 0.8651
Epoch 485/500
8000/8000 [==============================] - 2s 260us/step - loss: 0.3324 - acc: 0.8639
Epoch 486/500
8000/8000 [==============================] - 2s 259us/step - loss: 0.3325 - acc: 0.8662
Epoch 487/500
8000/8000 [==============================] - 2s 253us/step - loss: 0.3321 - acc: 0.8629
Epoch 488/500
8000/8000 [==============================] - 2s 230us/step - loss: 0.3315 - acc: 0.8647
Epoch 489/500
8000/8000 [==============================] - 2s 254us/step - loss: 0.3323 - acc: 0.8651
Epoch 490/500
8000/8000 [==============================] - 2s 241us/step - loss: 0.3321 - acc: 0.8649
Epoch 491/500
8000/8000 [==============================] - 2s 244us/step - loss: 0.3321 - acc: 0

In [21]:
classifier.fit(X_test,Y_test,batch_size=10,epochs =500)

Epoch 1/500
2000/2000 [==============================] - 0s 206us/step - loss: 0.3389 - acc: 0.8620
Epoch 2/500
2000/2000 [==============================] - 1s 253us/step - loss: 0.3352 - acc: 0.8615
Epoch 3/500
2000/2000 [==============================] - 1s 260us/step - loss: 0.3329 - acc: 0.8645
Epoch 4/500
2000/2000 [==============================] - 1s 251us/step - loss: 0.3321 - acc: 0.8615
Epoch 5/500
2000/2000 [==============================] - 0s 244us/step - loss: 0.3316 - acc: 0.8625
Epoch 6/500
2000/2000 [==============================] - 0s 250us/step - loss: 0.3311 - acc: 0.8640
Epoch 7/500
2000/2000 [==============================] - 0s 232us/step - loss: 0.3298 - acc: 0.8620
Epoch 8/500
2000/2000 [==============================] - 0s 225us/step - loss: 0.3294 - acc: 0.8610
Epoch 9/500
2000/2000 [==============================] - 0s 244us/step - loss: 0.3283 - acc: 0.8640
Epoch 10/500
2000/2000 [==============================] - 0s 223us/step - loss: 0.3282 - acc: 0.8645

2000/2000 [==============================] - 1s 251us/step - loss: 0.3196 - acc: 0.8700
Epoch 82/500
2000/2000 [==============================] - 0s 238us/step - loss: 0.3188 - acc: 0.8725
Epoch 83/500
2000/2000 [==============================] - 0s 239us/step - loss: 0.3193 - acc: 0.8705
Epoch 84/500
2000/2000 [==============================] - 1s 260us/step - loss: 0.3192 - acc: 0.8680
Epoch 85/500
2000/2000 [==============================] - 0s 238us/step - loss: 0.3187 - acc: 0.8700
Epoch 86/500
2000/2000 [==============================] - 1s 263us/step - loss: 0.3183 - acc: 0.8735
Epoch 87/500
2000/2000 [==============================] - 0s 184us/step - loss: 0.3186 - acc: 0.8710
Epoch 88/500
2000/2000 [==============================] - 0s 185us/step - loss: 0.3188 - acc: 0.8700
Epoch 89/500
2000/2000 [==============================] - 0s 230us/step - loss: 0.3190 - acc: 0.8710
Epoch 90/500
2000/2000 [==============================] - 0s 216us/step - loss: 0.3180 - acc: 0.8695
Epo

2000/2000 [==============================] - 0s 230us/step - loss: 0.3152 - acc: 0.8720
Epoch 162/500
2000/2000 [==============================] - 1s 273us/step - loss: 0.3150 - acc: 0.8730
Epoch 163/500
2000/2000 [==============================] - 0s 243us/step - loss: 0.3140 - acc: 0.8720
Epoch 164/500
2000/2000 [==============================] - 1s 284us/step - loss: 0.3146 - acc: 0.8745
Epoch 165/500
2000/2000 [==============================] - 0s 235us/step - loss: 0.3144 - acc: 0.8775
Epoch 166/500
2000/2000 [==============================] - 1s 257us/step - loss: 0.3140 - acc: 0.8740
Epoch 167/500
2000/2000 [==============================] - 0s 238us/step - loss: 0.3147 - acc: 0.8720
Epoch 168/500
2000/2000 [==============================] - 0s 244us/step - loss: 0.3136 - acc: 0.8730
Epoch 169/500
2000/2000 [==============================] - 0s 233us/step - loss: 0.3138 - acc: 0.8745
Epoch 170/500
2000/2000 [==============================] - 0s 243us/step - loss: 0.3137 - acc: 0

2000/2000 [==============================] - 0s 188us/step - loss: 0.3120 - acc: 0.8760
Epoch 242/500
2000/2000 [==============================] - 0s 194us/step - loss: 0.3116 - acc: 0.8745
Epoch 243/500
2000/2000 [==============================] - 0s 240us/step - loss: 0.3117 - acc: 0.8785
Epoch 244/500
2000/2000 [==============================] - 0s 172us/step - loss: 0.3114 - acc: 0.8730
Epoch 245/500
2000/2000 [==============================] - 0s 170us/step - loss: 0.3121 - acc: 0.8765
Epoch 246/500
2000/2000 [==============================] - 0s 210us/step - loss: 0.3115 - acc: 0.8735
Epoch 247/500
2000/2000 [==============================] - 0s 185us/step - loss: 0.3117 - acc: 0.8750
Epoch 248/500
2000/2000 [==============================] - 0s 185us/step - loss: 0.3120 - acc: 0.8770
Epoch 249/500
2000/2000 [==============================] - 0s 196us/step - loss: 0.3116 - acc: 0.8760
Epoch 250/500
2000/2000 [==============================] - 0s 167us/step - loss: 0.3116 - acc: 0

2000/2000 [==============================] - 0s 223us/step - loss: 0.3099 - acc: 0.8740
Epoch 322/500
2000/2000 [==============================] - 0s 214us/step - loss: 0.3094 - acc: 0.8735
Epoch 323/500
2000/2000 [==============================] - 0s 247us/step - loss: 0.3106 - acc: 0.8740
Epoch 324/500
2000/2000 [==============================] - 0s 232us/step - loss: 0.3107 - acc: 0.8750
Epoch 325/500
2000/2000 [==============================] - 0s 225us/step - loss: 0.3112 - acc: 0.8750
Epoch 326/500
2000/2000 [==============================] - 0s 243us/step - loss: 0.3110 - acc: 0.8745
Epoch 327/500
2000/2000 [==============================] - 0s 227us/step - loss: 0.3102 - acc: 0.8735
Epoch 328/500
2000/2000 [==============================] - 0s 241us/step - loss: 0.3108 - acc: 0.8755
Epoch 329/500
2000/2000 [==============================] - 0s 222us/step - loss: 0.3106 - acc: 0.8785
Epoch 330/500
2000/2000 [==============================] - 0s 231us/step - loss: 0.3106 - acc: 0

2000/2000 [==============================] - 0s 201us/step - loss: 0.3097 - acc: 0.8750
Epoch 402/500
2000/2000 [==============================] - 0s 181us/step - loss: 0.3108 - acc: 0.8780
Epoch 403/500
2000/2000 [==============================] - 0s 186us/step - loss: 0.3099 - acc: 0.8740
Epoch 404/500
2000/2000 [==============================] - 0s 205us/step - loss: 0.3101 - acc: 0.8770
Epoch 405/500
2000/2000 [==============================] - 0s 183us/step - loss: 0.3102 - acc: 0.8725
Epoch 406/500
2000/2000 [==============================] - 0s 198us/step - loss: 0.3111 - acc: 0.8760
Epoch 407/500
2000/2000 [==============================] - 1s 254us/step - loss: 0.3099 - acc: 0.8770
Epoch 408/500
2000/2000 [==============================] - 0s 227us/step - loss: 0.3106 - acc: 0.8735
Epoch 409/500
2000/2000 [==============================] - 0s 235us/step - loss: 0.3116 - acc: 0.8770
Epoch 410/500
2000/2000 [==============================] - 0s 243us/step - loss: 0.3101 - acc: 0

2000/2000 [==============================] - 0s 182us/step - loss: 0.3094 - acc: 0.8750
Epoch 482/500
2000/2000 [==============================] - 0s 195us/step - loss: 0.3090 - acc: 0.8740
Epoch 483/500
2000/2000 [==============================] - 0s 189us/step - loss: 0.3089 - acc: 0.8740
Epoch 484/500
2000/2000 [==============================] - 0s 186us/step - loss: 0.3096 - acc: 0.8780
Epoch 485/500
2000/2000 [==============================] - 0s 199us/step - loss: 0.3090 - acc: 0.8770
Epoch 486/500
2000/2000 [==============================] - 0s 188us/step - loss: 0.3091 - acc: 0.8760
Epoch 487/500
2000/2000 [==============================] - 0s 180us/step - loss: 0.3097 - acc: 0.8715
Epoch 488/500
2000/2000 [==============================] - 0s 189us/step - loss: 0.3091 - acc: 0.8775
Epoch 489/500
2000/2000 [==============================] - 0s 193us/step - loss: 0.3086 - acc: 0.8750
Epoch 490/500
2000/2000 [==============================] - 0s 181us/step - loss: 0.3089 - acc: 0

In [22]:
pred_y = classifier.predict(X_test)
pred_y = (pred_y>0.5)

In [23]:
pred_y

array([[False],
       [False],
       [False],
       ...,
       [ True],
       [False],
       [False]])

In [24]:
classifier.evaluate(X_test,Y_test)

2000/2000 [==============================] - 0s 58us/step


[0.30444934594631196, 0.877]